.gitignore, everviz/everest_hooks.py, everviz/main.py, setup.py, tests/unit/test_hook_implementation.py
This will be a fairly small PR, just to introduce the hook implementation.
solves: #2
=> Add hook impl

everviz/everest_hooks.py, setup.py
=> Add everest entry point

everviz/config.py, everviz/everest_hooks.py, tests/unit/test_everviz_config.py
=> Create the everviz webviz config file inside everest_output/everviz

tests/unit/test_formatting.py
=> Check black tests are working properly 

everviz/config.py, everviz/everest_hooks.py, everviz/log.py
=> Add logging to everviz 

everviz/config.py, everviz/everest_hooks.py, everviz/pages/controls.py, tests/unit/test_control_plot_data.py, tests/unit/test_everviz_config.py
=> Add controls plot

everviz/config.py, everviz/everest_hooks.py, everviz/pages/configuration.py, everviz/util.py, tests/unit/test_control_plot_data.py, tests/unit/test_everviz_config.py, tests/unit/test_util.py
=> Add configuration page

everviz/config.py, everviz/pages/summary_values.py, everviz/plugins/summary_plot/summary_plot.py, tests/integration/summary_plot/test_summary_plot_integration.py, tests/unit/test_summary_plot.py
Added the option to plot individual simulations to the summary plot, much like the objective function plot was doing.
It should be fairly easy to generalize the SummaryPlot to a plugin that can  handle the objective functions also.
=> Add individual simulations plots to summary plot.

docs/conf.py, docs/index.rst, docs/installing_everviz.rst, docs/introduction.rst, docs/running_everviz.rst, tox.ini
Initial documentation for everviz
closes #40
=> Everviz documentation start

README.md, setup.py
=> Expand readme

everviz/pages/objectives.py, everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/summary_plot/summary_plot.py, tests/integration/objectives_plot/test_objectives_plot_integration.py, tests/integration/summary_plot/test_summary_plot_integration.py, tests/unit/test_objective_plot_data.py
Plot multiple objective functions. Changed the objective plot to separate multiple objective functions, providing a pull-down to select the desired functions. In addition a plot of the total objective values, the one optimized by everest is shown.
closes #51
=> Multiple objective plots

everviz/pages/objectives.py, tests/unit/test_objective_plot_data.py
When merging the last pull request #54, I forgot to apply some fixes.
=> Small fixes to the objective function code

everviz/plugins/objectives_plot/objectives_plot.py
=> Use Data as default option

everviz/pages/crossplot.py, tests/unit/crossplot/test_layout.py, tox.ini
=> Add help text to crossplots

everviz/config.py, everviz/everest_hooks.py, everviz/pages/configuration.py, everviz/pages/controls.py, everviz/pages/objectives.py, everviz/pages/summary_values.py, everviz/plugins/__init__.py, everviz/plugins/config_editor/config_editor.py, setup.py, tests/integration/config_editor/test_config_editor.py, tests/unit/test_everviz_config.py
=> Allow the user of Everviz to give their own webviz config

everviz/pages/objectives.py, tests/unit/test_single_objective_data.py
=> Remove "Weighted" from the plot title "Weighted objective plot"

everviz/plugins/crossplot/crossplot.py, everviz/plugins/crossplot/crossplot_indexed.py, everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/objectives_plot/single_objectives_plot.py, everviz/plugins/summary_plot/summary_plot.py
=> Enable CSV export for Everviz plot plugins

everviz/config.py, everviz/pages/deltaplot.py, everviz/plugins/__init__.py, everviz/plugins/delta_plot/delta_plot.py, setup.py, tests/integration/delta_plot/test_objectives_delta_plot_integration.py, tests/integration/delta_plot/test_summary_delta_plot_integration.py, tests/unit/test_delta_plot_data.py, tests/unit/test_everviz_config.py
Implement bar plots of the differences of both function values and summary keys, between the first and the best batch.
closes #80
=> Bar plot of difference between 1st and best batch

everviz/pages/deltaplot.py
This is a temporary fix that should be merged before everest pull request #1314 is merged. This will allow everybody to continue working on everviz until issue #98 is resolved
=> Temporary fix everest pull request  #1314

everviz/pages/objectives.py, everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/objectives_plot/util.py, tests/integration/objectives_plot/test_objectives_plot_integration.py, tests/unit/test_objective_plot_data.py
Add a filter field to select realizations used to plot the objective functions.
=> Add filtering of realizations to the objectives plot

everviz/plugins/objectives_plot/objectives_plot.py, tests/integration/objectives_plot/test_objectives_plot_integration.py, tests/unit/test_objective_plot_data.py
=> Show weighted and normalized objectives

everviz/plugins/objectives_plot/objectives_plot.py, tests/unit/test_delta_plot_data.py
Resolves #77
Draw each line with different colour. When several functions are
drawn, each function will be of different colour as before.
Also add a feature where hovering over a point will draw the
corresponding realization with a thicker full line, in order to be
able to track individual realizations in the case of several functions.
=> Visualize objective plot as dashed lines

everviz/pages/deltaplot.py, everviz/pages/summary_values.py, everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/summary_plot/summary_plot.py, everviz/plugins/summary_plot/util.py, everviz/plugins/summary_plot/wells_plot.py, tests/integration/objectives_plot/test_objectives_plot_integration.py, tests/unit/test_summary_callback.py, tests/unit/test_summary_plot.py
Closes: #120
Also, we should check if this solution solved #115
=> Remove summary keys columns that have only NaN values

everviz/plugins/delta_plot/delta_plot.py
=> Rename axis on delta plot

everviz/plugins/controls_plot/controls_plot.py, everviz/plugins/delta_plot/delta_plot.py, everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/objectives_plot/single_objectives_plot.py
=> Change axis type to int if plotting real or batch

everviz/everest_hooks.py
=> Handle Ctrl-C in order to show exit message when running Everviz.

everviz/config.py, everviz/pages/configuration.py, everviz/pages/crossplot.py, everviz/pages/objectives.py, everviz/pages/summary_values.py, everviz/pages/wells_values.py, everviz/plugins/config_editor/config_editor.py, everviz/plugins/crossplot/callback/crossplot_callback.py, everviz/plugins/crossplot/crossplot.py, everviz/plugins/crossplot/crossplot_indexed.py, everviz/plugins/delta_plot/delta_plot.py, everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/objectives_plot/util.py, everviz/plugins/plugin_abc.py, everviz/plugins/summary_plot/summary_plot.py, everviz/plugins/summary_plot/wells_plot.py, setup.py, tests/unit/crossplot/test_layout.py, tests/unit/test_control_plot_data.py, tests/unit/test_everviz_config.py
Code formatting changes required by the latest version of black.
=> Black changes

everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/summary_plot/summary_plot.py, everviz/plugins/summary_plot/wells_plot.py, everviz/plugins/utils/layout/sidebar_layout.py, tests/integration/objectives_plot/test_objectives_plot_integration.py, tests/integration/summary_plot/test_summary_plot_integration.py, tests/integration/summary_plot/test_well_plot_integration.py, tests/unit/crossplot/test_layout.py
=> Show warning with number of realization when selecting statistics

everviz/plugins/summary_plot/summary_callback.py, tests/integration/summary_plot/test_well_plot_integration.py
=> Change summary statistics colors

everviz/plugins/controls_plot/controls_plot.py, everviz/plugins/crossplot/crossplot.py, everviz/plugins/crossplot/crossplot_indexed.py, everviz/plugins/delta_plot/delta_plot.py, everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/objectives_plot/single_objectives_plot.py, everviz/plugins/summary_plot/summary_plot.py, everviz/plugins/summary_plot/wells_plot.py, everviz/util.py
=> Directly download csv files from the everviz plugins

everviz/plugins/summary_plot/summary_callback.py, everviz/plugins/summary_plot/summary_plot.py, tests/unit/test_summary_callback.py
=> Allow multiple axis for summary plots

.github/workflows/publish_to_pypi.yml, .travis.yml
=> Pypi deploy workflow

everviz/data/load_csv/get_data.py
=> Fix bug caused by typo

everviz/plugins/controls_plot/controls_plot.py, everviz/plugins/crossplot/callback/crossplot_callback.py, everviz/plugins/objectives_plot/objectives_plot.py, everviz/plugins/objectives_plot/single_objectives_plot.py, everviz/plugins/summary_plot/summary_callback.py, tests/unit/test_summary_callback.py, tests/unit/test_summary_plot.py, tox.ini
Close: #158
Close: #159
Close: #160
All issues  #158, #159, #160 are solved by the same change :)
=> Scatter plot legend

everviz/plugins/summary_plot/summary_plot.py, everviz/plugins/utils/layout/sidebar_layout.py, tests/integration/summary_plot/test_summary_plot_integration.py
=> Limit summary value selection to two keys

everviz/components/list_select.py, everviz/plugins/gradient_plot.py, tests/conftest.py, tests/integration/gradient_plot/test_gradient_plot_integration.py
=> Add selectable control

.github/workflows/testing.yml, .pylintrc, README.md, everviz/everest_hooks.py, setup.py, tests/conftest.py, tests/integration/config_editor/test_config_editor.py, tests/integration/crossplot/test_crossplot_indexed_integration.py, tox.ini
=> Drop support for Python 3.6/3.7

pyproject.toml
=> Add webviz equinor theme to dependency list
